# Generated by Django 5.2.7 on 2025-11-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
